export const BETA_ERRORS = {
  INVALID_EMAIL: 'BETA_INVALID_EMAIL',
  DUPLICATE_IN_REQUEST: 'BETA_DUPLICATE_IN_REQUEST',
  INVALID_CODE_FORMAT: 'BETA_INVALID_CODE_FORMAT',
  CODE_NOT_FOUND: 'BETA_CODE_NOT_FOUND',
  CODE_EXPIRED: 'BETA_CODE_EXPIRED',
  CODE_ALREADY_REDEEMED: 'BETA_CODE_ALREADY_REDEEMED',
  CODE_REVOKED: 'BETA_CODE_REVOKED',
  EMAIL_MISMATCH: 'BETA_EMAIL_MISMATCH',
  NOT_AUTHENTICATED: 'BETA_NOT_AUTHENTICATED',
  FORBIDDEN_ADMIN: 'BETA_FORBIDDEN_ADMIN',
  RATE_LIMITED: 'BETA_RATE_LIMITED',
} as const;

export type BetaErrorCode = (typeof BETA_ERRORS)[keyof typeof BETA_ERRORS];
