export const ERROR_CODES = {
  // Generic errors
  NOT_FOUND: 'ERR_NOT_FOUND',
  BAD_REQUEST: 'ERR_BAD_REQUEST',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  FORBIDDEN: 'ERR_FORBIDDEN',
  INTERNAL_SERVER: 'ERR_INTERNAL_SERVER',

  AUTH_REQUIRED: 'ERR_AUTH_REQUIRED',
  ACCESS_DENIED: 'ERR_ACCESS_DENIED',

  // Prompt service errors
  PROMPT_GENERATION_FAILED: 'ERR_PROMPT_GENERATION_FAILED',
  INVALID_RESUME_TEXT: 'ERR_INVALID_RESUME_TEXT',
  INVALID_JOB_DESCRIPTION: 'ERR_INVALID_JOB_DESCRIPTION',
  INVALID_COMPANY_NAME: 'ERR_INVALID_COMPANY_NAME',
  INVALID_ANALYSIS_DATA: 'ERR_INVALID_ANALYSIS_DATA',
  UNSUPPORTED_FILE_TYPE: 'ERR_UNSUPPORTED_FILE_TYPE',

  // Rate limit errors
  RATE_LIMIT_EXCEEDED: 'ERR_RATE_LIMIT_EXCEEDED',
  USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
  INVALID_TEMPLATE_TYPE: 'ERR_INVALID_TEMPLATE_TYPE',
  RESUME_TEMPLATE_NOT_FOUND: 'ERR_RESUME_TEMPLATE_NOT_FOUND',
  INVALID_USER_CONTEXT: 'ERR_INVALID_USER_CONTEXT',

  FAILED_TO_PARSE_ATS_EVALUATION_JSON:
    'ERR_FAILED_TO_PARSE_ATS_EVALUATION_JSON',
} as const;

// Type for error codes
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
