export const RESUME_EXTRACTION_PROMPT_VERSION = 'v1.0';
export const JD_ANALYSIS_PROMPT_VERSION = 'v1.0';
export const RESUME_OPTIMIZATION_PROMPT_VERSION = 'v1.0';
export const PRECISION_OPTIMIZATION_PROMPT_VERSION = 'v1.0';
export const PROFILE_QUESTION_GEN_PROMPT_VERSION = 'v1.0';
export const PROFILE_ENRICHMENT_PROMPT_VERSION = 'v1.0';
export const COVER_LETTER_PROMPT_VERSION = 'v1.0';
