export const RESUME_EXTRACTION_PROMPT_VERSION = 'v1.1';
export const JD_ANALYSIS_PROMPT_VERSION = 'v1.1';
export const OPTIMIZATION_PROMPT_VERSION = 'v2.3';
export const PROFILE_QUESTION_GEN_PROMPT_VERSION = 'v1.0';
export const PROFILE_ENRICHMENT_PROMPT_VERSION = 'v1.0';
export const COVER_LETTER_PROMPT_VERSION = 'v1.0';
