import { FieldSelectionConfig } from '../../../shared/services/field-selection.service';

export const JOB_APPLICATION_FIELD_CONFIG: FieldSelectionConfig = {
  entity: 'jobApplication',
  allowedFields: [
    'id',
    'company_name',
    'job_position',
    'job_description',
    'job_url',
    'job_location',
    'employment_type',
    'work_mode',
    'salary_min',
    'salary_max',
    'salary_currency',
    'pay_period',
    'salary_negotiable',
    'status',
    'application_source',
    'job_board_source',
    'applied_via',
    'priority',
    'tags',
    'application_deadline',
    'applied_at',
    'decision_deadline',
    'next_action',
    'cover_letter',
    'notes',
    'recruiter_name',
    'recruiter_email',
    'recruiter_phone',
    'hiring_manager_name',
    'hiring_manager_email',
    'contact_phone',
    'contacts',
    'interview_scheduled_at',
    'interview_notes',
    'follow_up_date',
    'rejection_stage',
    'rejection_reason',
    'rejection_feedback_received',
    'compensation_offer',
    'attachments',
    'status_history',
    'metadata',
    'created_at',
    'updated_at',
    'user_id',
  ],
  defaultFields: [
    'id',
    'company_name',
    'job_position',
    'status',
    'application_source',
    'applied_at',
    'created_at',
    'updated_at',
  ],
  relations: {
    user: {
      entity: 'user',
      allowedFields: ['id', 'email', 'firstName', 'lastName'],
    },
    resume_generation: {
      entity: 'resume_generation',
      allowedFields: ['id', 'template_name', 'created_at'],
    },
  },
};
