import {
  Column,
  Entity,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
  OneToMany,
} from 'typeorm';
import { User } from './user.entity';
import { Resume } from './resume.entity';

/**
 * Tailoring Session Entity
 *
 * Represents a single session of the question-based resume tailoring process.
 * Tracks the entire workflow from initial submission through question generation
 * to final resume generation.
 *
 * Lifecycle:
 * 1. created - Session initialized with job details and resume
 * 2. questions_generated - AI has generated questions for user
 * 3. responses_submitted - User has provided answers to questions
 * 4. resume_generating - Resume generation in progress
 * 5. completed - Tailored resume successfully generated
 * 6. failed - Process failed at any stage
 */
@Entity({ name: 'tailoring_sessions' })
export class TailoringSession {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'user_id', nullable: true })
  userId: string;

  @Column({ name: 'guest_id', nullable: true })
  guestId: string;

  @Column({ name: 'resume_id', nullable: true })
  resumeId: string;

  @Column({ name: 'job_position', type: 'varchar', length: 100 })
  jobPosition: string;

  @Column({ name: 'company_name', type: 'varchar', length: 100 })
  companyName: string;

  @Column({ name: 'job_description', type: 'text' })
  jobDescription: string;

  @Column({ name: 'template_id' })
  templateId: string;

  @Column({
    name: 'status',
    type: 'varchar',
    length: 50,
    default: 'created',
  })
  status: string; // created | questions_generated | responses_submitted | resume_generating | completed | failed

  @Column({ name: 'resume_file_name', nullable: true })
  resumeFileName: string;

  @Column({ name: 'resume_file_size', nullable: true })
  resumeFileSize: number;

  @Column({ name: 'resume_content', type: 'text', nullable: true })
  resumeContent: string;

  @Column({ name: 'questions_generated_at', type: 'timestamp', nullable: true })
  questionsGeneratedAt: Date;

  @Column({ name: 'responses_submitted_at', type: 'timestamp', nullable: true })
  responsesSubmittedAt: Date;

  @Column({
    name: 'resume_generation_completed_at',
    type: 'timestamp',
    nullable: true,
  })
  resumeGenerationCompletedAt: Date;

  @Column({ name: 'queue_message_id', nullable: true })
  queueMessageId: string;

  @Column({
    name: 'result_metadata',
    type: 'jsonb',
    nullable: true,
  })
  resultMetadata: Record<string, any>;

  @Column({ name: 'error_message', type: 'text', nullable: true })
  errorMessage: string;

  @Column({ name: 'is_active', type: 'boolean', default: true })
  isActive: boolean;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;

  @ManyToOne(() => User, { nullable: true })
  @JoinColumn({ name: 'user_id' })
  user: User;

  @ManyToOne(() => Resume, { nullable: true })
  @JoinColumn({ name: 'resume_id' })
  resume: Resume;

  @OneToMany(() => TailoringQuestion, (question) => question.session, {
    cascade: true,
  })
  questions: TailoringQuestion[];
}

/**
 * Tailoring Question Entity
 *
 * Represents individual questions generated by AI to gather business impact
 * information from the user. Each question targets specific work experience
 * bullet points to obtain quantifiable metrics and facts.
 */
@Entity({ name: 'tailoring_questions' })
export class TailoringQuestion {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'session_id' })
  sessionId: string;

  @Column({ name: 'work_experience_index', type: 'int' })
  workExperienceIndex: number;

  @Column({ name: 'bullet_point_index', type: 'int' })
  bulletPointIndex: number;

  @Column({ name: 'original_bullet_point', type: 'text' })
  originalBulletPoint: string;

  @Column({ name: 'question_text', type: 'text' })
  questionText: string;

  @Column({ name: 'question_category', type: 'varchar', length: 50 })
  questionCategory: string; // metrics | impact | scope | technology | outcome

  @Column({ name: 'user_response', type: 'text', nullable: true })
  userResponse: string;

  @Column({ name: 'is_answered', type: 'boolean', default: false })
  isAnswered: boolean;

  @Column({ name: 'order_index', type: 'int' })
  orderIndex: number;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;

  @ManyToOne(() => TailoringSession, (session) => session.questions, {
    onDelete: 'CASCADE',
  })
  @JoinColumn({ name: 'session_id' })
  session: TailoringSession;
}
