export const TailoredContentJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    title: { type: 'string' },
    contactInfo: {
      type: 'object',
      additionalProperties: false,
      properties: {
        name: { type: 'string' },
        email: { type: 'string' },
        phone: { type: 'string' },
        location: { type: 'string' },
        linkedin: { type: 'string' },
        portfolio: { type: 'string' },
        github: { type: 'string' },
      },
      required: [
        'name',
        'email',
        'phone',
        'location',
        'linkedin',
        'portfolio',
        'github',
      ],
    },
    summary: { type: 'string' },
    skills: {
      type: 'object',
      additionalProperties: false,
      properties: {
        languages: { type: 'array', items: { type: 'string' } },
        frameworks: { type: 'array', items: { type: 'string' } },
        tools: { type: 'array', items: { type: 'string' } },
        databases: { type: 'array', items: { type: 'string' } },
        concepts: { type: 'array', items: { type: 'string' } },
      },
      required: ['languages', 'frameworks', 'tools', 'databases', 'concepts'],
    },
    experience: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          company: { type: 'string' },
          position: { type: 'string' },
          duration: { type: 'string' },
          location: { type: 'string' },
          responsibilities: { type: 'array', items: { type: 'string' } },
          achievements: { type: 'array', items: { type: 'string' } },
          startDate: { type: 'string' },
          endDate: { type: 'string' },
          technologies: { type: 'string' },
        },
        required: [
          'company',
          'position',
          'duration',
          'location',
          'responsibilities',
          'achievements',
          'startDate',
          'endDate',
          'technologies',
        ],
      },
    },
    education: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          institution: { type: 'string' },
          degree: { type: 'string' },
          major: { type: 'string' },
          startDate: { type: 'string' },
          endDate: { type: 'string' },
        },
        required: ['institution', 'degree', 'major', 'startDate', 'endDate'],
      },
    },
    certifications: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          name: { type: 'string' },
          issuer: { type: 'string' },
          date: { type: 'string' },
          expiryDate: { type: 'string' },
          credentialId: { type: 'string' },
        },
        required: ['name', 'issuer', 'date', 'expiryDate', 'credentialId'],
      },
    },
    additionalSections: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          title: { type: 'string' },
          items: { type: 'array', items: { type: 'string' } },
        },
        required: ['title', 'items'],
      },
    },
  },
  required: [
    'title',
    'contactInfo',
    'summary',
    'skills',
    'experience',
    'education',
    'certifications',
    'additionalSections',
  ],
} as const;
