export enum AwsConfigKeys {
    AWS_S3_EMAIL_TEMPLATES_BUCKET = 'AWS_S3_EMAIL_TEMPLATES_BUCKET',
    AWS_S3_RESUME_TEMPLATES_BUCKET = 'AWS_S3_RESUME_TEMPLATES_BUCKET',
    AWS_S3_CANDIDATES_RESUMES_BUCKET = 'AWS_S3_CANDIDATES_RESUMES_BUCKET',
    AWS_BUCKET_REGION = 'AWS_BUCKET_REGION',
    AWS_REGION = 'AWS_REGION',
    AWS_SES_USER_ACCESS_KEY_ID = 'AWS_SES_USER_ACCESS_KEY_ID',
    AWS_SES_USER_SECRET_ACCESS_KEY = 'AWS_SES_USER_SECRET_ACCESS_KEY',
    AWS_SES_FROM_EMAIL = 'AWS_SES_FROM_EMAIL',
    AWS_SES_FROM_NAME = 'AWS_SES_FROM_NAME'
}